name: JamesArthurFoto
favicon: null
layout_spectrum: 0.08887
typography_spectrum: 0.92989
title: Photography by James Arthur Smith
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#323232'
    - '#535353'
    - '#737373'
    - '#f0f0f0'
    - '#bababa'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
